---
- name: Pull and start database container
  community.docker.docker_container:
    recreate: true
    name: "{{ database_container_name }}"
    image: "medhydohoucpe/database:main"
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_database_name }}"
    networks:
      - name: "{{ app_docker_network_name }}"

- name: Check database container status
  community.docker.docker_container_info:
    name: "{{ database_container_name }}"
  register: result
  notify: Check database container inspection result

- name: Fail if database container isn't running
  ansible.builtin.fail:
    msg: "The database container failed to start : exit code {{ result.container.State.ExitCode }} (error : {{ result.container.State.Error }})"
  when: not result.container.State.Running
