---
- name: Pull and start httpd container
  community.docker.docker_container:
    recreate: true
    name: "{{ httpd_container_name }}"
    image: "medhydohoucpe/httpd:main"
    published_ports:
      - "80:80"
    networks:
      - name: "{{ app_docker_network_name }}"

- name: Check httpd container status
  community.docker.docker_container_info:
    name: "{{ httpd_container_name }}"
  register: result

- name: Fail if httpd container isn't running
  ansible.builtin.fail:
    msg: "The api container failed to start : exit code {{ result.container.State.ExitCode }} (error : {{ result.container.State.Error }})"
  when: not result.container.State.Running
