---
- name: Install containers on all hosts
  hosts: all
  gather_facts: false
  become: true
  roles:
    - docker
    - create_app_network
    - httpd
    - db
    - api
    - front
  vars:
    app_docker_network_name: "app-network"
