---
- name: Create network if it doesn't exist
  community.docker.docker_network:
    name: "{{ app_docker_network_name }}"

- name: Pull and start api container
  community.docker.docker_container:
    recreate: true
    name: backend
    image: "medhydohoucpe/api:main"
    env:
      DATABASE_USER: usr
      DATABASE_PASSWORD: pwd
      DATABASE_NAME: db
      DATABASE_URL: database
      DATABASE_PORT: "5432"
    networks:
      - name: "{{ app_docker_network_name }}"

- name: Check database container status
  docker_container_info:
    name: backend
  register: result

- name: Fail if api container isn't running
  fail:
    msg: "The api container failed to start : exit code {{ result.container.State.ExitCode }} (error : {{ result.container.State.Error }})"
  when: not result.container.State.Running