name: ansible-check
on:
  push:
    paths:
      - "ansible/**"
  pull_request:
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./ansible
    outputs:
      success: ${{ job.status == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Install ansible-lint with pip
        run: |
          sudo apt update
          sudo apt install pip git
          pip install ansible-core ansible-lint

      - name: Run ansible-lint on our playbook
        run: |
          ansible-galaxy collection install -r requirements.yml
          ansible-lint -v -s --project-dir .
