name: ansible-check
on:
  push:
    paths:
      - "ansible/**"
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Install ansible-lint with pip
        run: |
          sudo apt update
          sudo apt install pip git
          pip install ansible-core ansible-lint

      - name: Run ansible-lint on our playbook
        run: |
          cat ${{secrets.VAULT_PASSWORD}} >> .ansible_vault_pass
          ansible-galaxy collection install -r requirements.yml
          ansible-lint -v -s --exclude ./vars/* --project-dir .
