on:
  workflow_run:
    workflows: ["ansible-check"]
    branches: [main]
    types: 
      - completed

jobs:
    deploy-to-prod:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2.5.0
            - name: Deploy to prod
              if: ${{ github.event.workflow_run.conclusion == 'success' }}
              uses: dawidd6/action-ansible-playbook@v2
              with:
                directory: ./ansible
                playbook: playbook.yml
                known_hosts: |
                  medhy.dohou.takima.cloud ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN2lupj45sVom4e+f+1ifTxJTfW2TsKqyClld2s4kUvW
                inventory: inventories/setup.yml