on:
    workflow_run: 

jobs:
    deploy-to-prod:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2.5.0
            - name: Automatically accept new HostKey
              run: echo "StrictHostKeyChecking=accept-new" > ~/.ssh/config
            - name: Deploy to prod
              if: ${{ github.run.workflow_runs[needs.ansible-check.outputs.success].conclusion == 'success' }}
              uses: dawidd6/action-ansible-playbook@v2
              with:
                directory: ./ansible
                playbook: playbook.yml