on:
    workflow_run: 

jobs:
    deploy-to-prod:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2.5.0
            - name: Deploy to prod
              uses: ${{ github.run.workflow_runs[needs.ansible-check.outputs.success].conclusion == 'success' }}