on:
  workflow_run:
    workflows:
      - "test.yml"
    types:
      - completed
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Release pipeline
jobs:
  # define job to build and publish docker image
  build-and-push-docker-image-release:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    env:
      DOCKERHUB_TAG: ${{ github.ref_name }}
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          file: ./Dockerfile.api
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/api:${{ env.DOCKERHUB_TAG }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          file: ./Dockerfile.db
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/database:${{ env.DOCKERHUB_TAG }}
          

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          file: ./Dockerfile.http
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/httpd:${{ env.DOCKERHUB_TAG }}